### ISSUE TITLE
Add Atom as editor

### ISSUE THREAD

**Issue by Chronophylos** [warpdragon/aaa#4]
Atom editor has a port of the Sublime Text 3 KV syntax package: https://atom.io/packages/language-dotakv by Faultless
Install with `apm install language-dotakv`
or in Settings -> Install: search for `language-dotakv`.

He also ported https://atom.io/packages/language-dotalua

**Comment by warpdragon** [comment]
k

**Comment by Chronophylos** [comment]
BTW you can close issues of others on your own repo.
